// Generated by https://quicktype.io

export interface CofeResponse {
    title:       string;
    description: string;
    ingredients: string[];
    image:       string;
    id:          number;
}
// Generated by https://quicktype.io
export interface ProductsResponse {
    id:                number;
    name:              string;
    price:             number;
    category:          string;
    unit:              string;
    supliers_id:       string;
    restaurante_id:    string;
    more_seller:       boolean;
    min_stock:         number;
    stock:             number;
    itbms:             number;
    price_for_unit:    number;
    unit_presentation: number;
}

export interface ReqResUser {
    page:        number;
    per_page:    number;
    total:       number;
    total_pages: number;
    data:        User[];
    support:     Support;
}

export interface User {
    id:         number;
    email:      string;
    first_name: string;
    last_name:  string;
    avatar:     string;
}

export interface Support {
    url:  string;
    text: string;
}
